class Strings {
  static const String DASTUR_NOMI = "Futbol Clab";

  static const List<String> ISIMLARI_TURI = [
    "Leo Messi",
    "Neymar Jr",
    "Cristiano Ronaldo",
    "Sadio Mane",
    "Muhammad Salah",
    "Sterling",
    "Pol Pogba",
    "Kelian Mbappe",
    "Antuan Grizman",
    "Harriy Keyn",
    "Artur Vidal",
    "Ter Shtegin",
    "Jorde Alba",
  ];

  static const List<String> FOLOWER_LAR = [
    "1221 Friends",
    "122 Friends",
    "156 Friends",
    "18 Friends",
    "28 Friends",
    "45 Friends",
    "56 Friends",
    "950 Friends",
    "512 Friends",
    "442 Friends",
    "96 Friends",
    "695 Friends",
    "852 Friends",
  ];
  static const List<String> RASIM_LAR = [
    "assets/images/0.jpg",
    "assets/images/1.jpg",
    "assets/images/2.jpg",
    "assets/images/3.jpg",
    "assets/images/4.jpg",
    "assets/images/5.jpg",
    "assets/images/6.jpg",
    "assets/images/7.jpg",
    "assets/images/8.jpg",
    "assets/images/9.jpg",
    "assets/images/10.jpg",
    "assets/images/11.jpg",
    "assets/images/12.jpg",
  ];
  static const List<String> MALUMOT_LAR = [
    """Lionel Andres Messi (Ispancha talaffuzi: [ljoˈnel anˈdɾes ˈmesi]; Leo Messi nomi bilan ham tanilgan, (1987 yil 24-iyun) - argentinalik professional futbolchi, forvard sifatida o'ynaydi. Ispaniyaning "Barselona" klubi va Argentina terma jamoasining sardorlari. Ko'pincha dunyoning eng yaxshi o'yinchisi sifatida tanilgan va barcha zamonlarning eng zo'r o'yinchilaridan biri sifatida tanilgan Messi rekord darajadagi oltita "Oltin to'p" mukofotiga sazovor bo'ldi, rekord oltita Evropa "Oltin poyafzali" va 2020 yilda "Oltin to'p" ning orzular jamoasiga nomzod bo'lgan. U o'zining butun professional faoliyatini "Barselona" safida o'tkazgan va u erda 34 ta sovrinni yutgan, shu jumladan o'nta La Liga chempioni, etti marta Kubok. del Rey unvonlari va UEFA Chempionlar Ligasining to'rttasi.Mahsuldor gol muallifi va kreativ pleymeyker Messi La Liga (474), La Liga va Evropa ligasi mavsumida (50) eng ko'p gol urish, La Ligadagi eng ko'p xet-trik (36). ) va UEFA Chempionlar Ligasi (8) va La Liga (192) da eng ko'p golli pas, La Liga an d Evropa ligasi mavsumi (21) va Amerika Kubogi (12). U klub va mamlakat uchun karyerasida 750 dan ortiq gol urgan va bitta klub uchun eng ko'p gol urgan futbolchi.

Argentinaning markazida tug'ilib o'sgan Messi 13 yoshida "Barselona" safiga qo'shilish uchun Ispaniyaga ko'chib o'tdi va u uchun 2004 yil oktyabr oyida 17 yoshida raqobatbardosh debyutini o'tkazdi. U o'zini keyingi uch yil ichida klubning ajralmas o'yinchisi sifatida ko'rsatdi. 2008-09 yillarda birinchi uzluksiz mavsumda u "Barselona" ga Ispaniya futbolidagi birinchi treblga erishishda yordam berdi; o'sha yili 22 yoshida Messi o'zining birinchi "Oltin to'p" ini qo'lga kiritdi. Uch mavsum muvaffaqiyatli o'tdi, Messi ketma-ket to'rtta "Oltin to'p" ni qo'lga kiritdi va bu sovrinni to'rt marta va ketma-ket qo'lga kiritgan birinchi futbolchiga aylandi. [12] 2011–12 yilgi mavsumda u bir mavsumda eng ko'p gol urish bo'yicha La Liga va Evropa rekordlarini o'rnatdi, shu bilan birga o'zini «Barselona» ning eng yaxshi to'purari sifatida ko'rsatdi. Keyingi ikki mavsumda Messi "Oltin to'p" uchun Krishtianu Ronaldudan keyin ikkinchi o'rinni egalladi (uning karerasida tanilgan raqibi), 2014-15 mavsumida eng yaxshi formasini tiklaganidan oldin La Liganing eng yaxshi to'purari bo'ldi va "Barselona" ni etakchiga aylantirdi. tarixiy ikkinchi treble, shundan so'ng u 2015 yilda beshinchi "Oltin to'p" bilan taqdirlandi. Messi 2018 yilda "Barselona" sardorligini oldi va 2019 yilda u rekord darajadagi oltinchi "Oltin to'p" ni qo'lga kiritdi.

Argentinalik futbolchi, Messi o'z mamlakatining eng yaxshi to'purari hisoblanadi. Yoshlik darajasida u 2005 yilgi yoshlar o'rtasidagi Jahon chempionatida g'olib chiqdi va musobaqani ham "Oltin to'p", ham "Oltin poyafzal" bilan yakunladi va 2008 yilgi yozgi Olimpiya o'yinlarida Olimpiya o'yinlarining oltin medalini oldi. Uning o'yin uslubi kichraytiruvchi, chap oyoqli dribler sifatida vatandoshi Diego Maradona bilan taqqoslaganda, u Messini uning vorisi deb ta'riflagan. 2005 yil avgust oyida katta debyutidan so'ng Messi 2006 yilgi nashr paytida FIFA Jahon kubogida o'ynagan va gol urgan eng yosh argentinalik bo'ldi va 2007 yil Amerika Kubogi finaliga qadar etib bordi va u erda musobaqaning yosh o'yinchisi deb topildi. 2011 yil avgustidan tarkib sardori sifatida u Argentinani ketma-ket uchta finalga olib bordi: 2014 yilgi Jahon kubogi, u uchun "Oltin to'p" va 2015 va 2016 yillarda Amerika Kubogi. 2016 yilda xalqaro faoliyatini yakunlashini e'lon qilgandan so'ng, u qarorini o'zgartirib, o'z mamlakatini 2018 FIFA Jahon kubogi saralashiga olib chiqdi va 2019 yilda Amerika Kubogida uchinchi o'rinni egalladi.

Messi 2006 yildan beri Adidas sport kiyimlarini ishlab chiqarishni qo'llab-quvvatlamoqda. France Football ma'lumotlariga ko'ra, u 2009-2014 yillar oralig'ida olti yil ichida dunyoning eng ko'p maosh oluvchi futbolchisi bo'lgan va Forbes tomonidan 2019 yilda dunyoning eng ko'p maosh oluvchi sportchisi sifatida qayd etilgan. Messi orasida 2011 va 2012 yillarda Time dunyoning eng nufuzli 100 kishisi. 2020 yil fevral oyida u Laureus dunyoning eng yaxshi sportchisi mukofotiga sazovor bo'ldi va shu tariqa ushbu sovrinni qo'lga kiritgan birinchi futbolchi va shuningdek birinchi jamoaviy sportchi bo'ldi. O'sha yilning oxirida Messi ikkinchi milliarder bo'ldi (va ikkinchi sport turi bo'yicha sportchi) mansab daromadidan 1 milliard dollardan oshib ketdi. """,
    """Neymar da Silva Santos Xunior (1992 yil 5 fevralda tug'ilgan), Neymar nomi bilan tanilgan, braziliyalik professional futbolchi, Liga 1 klubi Parij Sen-Jermeni va Braziliya terma jamoasining forvardi sifatida o'ynaydi. U dunyoning eng yaxshi o'yinchilaridan biri sifatida tan olingan.

Neymar 17 yoshida o'zining professional debyutini "Santos" da boshlagan, u klubga ketma-ket ikkita Campeonato Paulista chempionligini, Braziliya Kubogi va 2011 Libertadores kubogini yutishda yordam bergan; Ikkinchisi - 1963 yildan beri Santosning birinchi o'yini. Neymar 2011 va 2012 yillarda ikki marta Janubiy Amerikaning yilning eng yaxshi futbolchisi deb topildi va tez orada Evropaga ko'chib, "Barselona" safiga qo'shildi. "Barselona" ning Lionel Messi va Luis Suares bilan hujum uchligi tarkibida u La Liga, Ispaniya kubogi va UEFA Chempionlar Ligasining qit'a treblini qo'lga kiritdi va 2015 yildagi o'yinlari uchun FIFA Oltin to'pi uchun uchinchi o'rinni egalladi. Keyin u 2015–16 yilgi mavsumda ichki dublga erishdi. 2017 yilda Neymar 222 million yevro evaziga Parij Sen-Jermenga o'tdi va shu tariqa u eng qimmat futbolchiga aylandi. Frantsiyada Neymar uchta liga chempioni, uchta Frantsiya kubogi va ikkita Lupa kubogini qo'lga kiritdi. Bu tarkibda ichki trebl bor edi va debyut mavsumida Liga 1 ning eng yaxshi o'yinchisi deb tan olindi. Neymar 2019-2020 yilgi mavsumda PSJga ichki to'rtlikka erishishda yordam berdi va klubni ilk bor Chempionlar Ligasi finaliga olib chiqdi.

18 yoshida debyut qilganidan buyon Braziliya terma jamoasi safida 106 uchrashuvda 67 gol urgan Neymar o'z terma jamoasining eng yuqori to'purarlari orasida ikkinchi o'rinda bormoqda va faqatgina Peleni ortda qoldirmoqda. U Braziliyaning 2011 yilgi Janubiy Amerika yoshlar chempionatida etakchi gol muallifi sifatida yakunlagan g'alabalarida va 2013 yilgi FIFA Konfederatsiyalar kubogida muhim rol o'ynagan va musobaqa futbolchisi sifatida "Oltin to'p" ni qo'lga kiritgan. Uning Braziliya terma jamoasi sardori sifatida 2016 yilgi yozgi Olimpiya o'yinlarida erkaklar futbolidagi birinchi Olimpiya oltin medaliga sazovor bo'lishidan oldin uning 2014 yilgi Jahon chempionati va 2015 yilgi Amerika Kubogidagi ishtiroki jarohat va diskvalifikatsiya tufayli qisqartirildi. Ikki yil o'tgach, u sardorlikdan voz kechib, JCh-2018da ishtirok etdi.

Maydon tashqarisida Neymar dunyoning eng taniqli sportchilari qatoriga kiradi. SportsPro uni 2012 va 2013 yillarda dunyoning eng xaridorgir sportchisi deb topdi va ESPN uni 2016 yilda dunyodagi eng mashhur to'rtinchi sportchi sifatida ko'rsatdi. 2017 yilda Time uni har yili dunyodagi eng nufuzli 100 kishining ro'yxatiga kiritdi. 2018 yilda France Football nashri Neymarni dunyodagi eng ko'p maosh oladigan uchinchi futbolchi deb topdi. Keyingi yili Forbes uni dunyodagi eng ko'p maosh oladigan uchinchi sportchi deb qayd etdi va 2020 yilda to'rtinchi o'ringa tushib ketdi.""",
    """Krishtianu Ronaldu dos Santos Aveiro GOIH ComM (portugalcha talaffuzi: [kɾiʃˈtjɐnu ʁɔˈnaɫdu]; 1985 yil 5 fevralda tug'ilgan) - portugaliyalik professional futbolchi, A Seriyaning "Yuventus" klubida forvard bo'lib o'ynaydi va Portugaliya terma jamoasining sardori. Ko'pincha dunyoning eng yaxshi o'yinchisi deb hisoblangan va barcha zamonlarning eng zo'r o'yinchilaridan biri sifatida tanilgan Ronaldu beshta "Oltin to'p" mukofotiga sazovor bo'ldi va to'rtta Evropaning "Oltin poyafzallari" bu ikkalasi ham evropalik futbolchi uchun rekorddir. U faoliyati davomida 32 ta asosiy sovrinni qo'lga kiritgan, shu jumladan etti marta chempionlik unvonlari, beshta UEFA Chempionlar Ligasi, bitta UEFA Evropa chempionati va bitta UEFA Millatlar Ligasi chempioni. Ronaldu Chempionlar Ligasida eng ko'p gol urish (134) va Evropa chempionatida eng ko'p gol urish (11) bo'yicha rekordchiga ega. U professional karerada 1100 dan ortiq o'yin o'tkazgan va 780 dan ortiq klub va mamlakat uchun yuqori martaba gollarini urgan kam sonli futbolchilardan biridir. Shuningdek, u 100 xalqaro gol urgan ikkinchi erkak va bu yutuqqa erishgan birinchi evropalik erkak.

  Madeyrada tug'ilib o'sgan Ronaldu o'zining katta klubdagi faoliyatini Sporting CPda boshlagan, 2003 yilda 18 yoshida "Manchester Yunayted" bilan shartnoma imzolagan, u birinchi mavsumida Angliya kubogini yutganidan so'ng, "Yunayted" ga ketma-ket uchta chempionlik chempioni bo'lishiga yordam bergan. Liga va FIFA klublar o'rtasidagi jahon chempionati; 23 yoshida u o'zining birinchi "Oltin to'p" ini qo'lga kiritdi. 2009 yilda Ronaldu "Real" ga 94 million evro (80 million funt) evaziga transfer qilinganida, o'sha paytdagi eng qimmat uyushma futbol transferi mavzusi bo'lgan. U erda u 15 ta sovrinni qo'lga kiritdi, ikkitasi La Liga, ikkita Kopas del Rey va to'rtta Chempionlar Ligasi chempioni va klubning eng yaxshi to'purari bo'ldi. Madridga qo'shilgandan so'ng Ronaldu 2013-2014 yillarda va yana 2016-2017 yillarda "Oltin to'p" ni qo'lga kiritguniga qadar uch marotaba "Oltin to'p" uchun ikkinchi o'rinni egallab, Lionel Messini ortda qoldirdi. 2018 yilda ketma-ket uchinchi marta Chempionlar Ligasida g'olib chiqqanidan so'ng, Ronaldu kubokni besh marta qo'lga kiritgan birinchi futbolchiga aylandi. 2018 yilda u "Yuventus" ga 100 million yevro (88 million funt) miqdoridagi transferni imzoladi, bu Italiya klubi tomonidan to'langan eng yuqori va 30 yoshdan oshgan futbolchi uchun eng yuqori narx. U klub bilan o'tkazgan dastlabki uch mavsumida A Seriyada ikkita g'oliblikni qo'lga kiritdi, ikkita Supercoppa Italiana va Coppa Italia.

  Ronaldu 2003 yil 18 yoshida Portugaliya terma jamoasida o'zining xalqaro miqyosdagi ilk debyutini o'tkazgan va shu vaqtdan beri o'n bitta yirik turnirda maydonga tushish va gol urishni o'z ichiga olgan 170 martadan ko'proq sovrin to'plab, Portugaliyaning eng ko'p maydonga tushgan futbolchisi va mamlakatining eng yaxshi to'purari bo'ldi. U o'zining birinchi xalqaro golini Evro-2004da urdi va u erda Portugaliyaning finalga chiqishiga yordam berdi va 2008 yil iyul oyida terma jamoaning to'liq sardorligini oldi. 2015 yilda Ronaldu Portugaliya Futbol Federatsiyasi tomonidan barcha davrlarning eng yaxshi portugal futbolchisi deb topildi. Keyingi yil u Portugaliyani yirik turnirda Evro-2016 g'olibligi bilan birinchi g'alabasiga olib keldi va turnirning ikkinchi eng yuqori to'purari sifatida kumush butsani oldi.

  Dunyoning eng taniqli va taniqli sportchilaridan biri bo'lgan Ronaldu 2016 va 2017 yillarda Forbes tomonidan dunyoning eng ko'p maosh oluvchi sportchisi va 2016 yildan 2019 yilgacha ESPN tomonidan dunyoning eng taniqli sportchisi sifatida qayd etilgan. Vaqt uni 100 ta eng yaxshi 100 ta ro'yxatiga kiritdi. 2014 yilda dunyodagi nufuzli insonlar. U o'z karerasida 1 milliard dollar ishlab topgan birinchi futbolchi, shuningdek faqat uchinchi sportchi.""",
    """Sadio Mane (1992 yil 10 aprelda tug'ilgan) - senegallik professional futbolchi, Premer-liganing «Liverpul» klubi va Senegal terma jamoasida vinger sifatida o'ynaydi. Dunyoning eng yaxshi o'yinchilaridan biri sifatida qaraladigan Mane 2019 yilgi "Oltin to'p" uchun to'rtinchi o'rinni egalladi va FIFAning eng yaxshi erkak futbolchisi mukofotida u 2019 yilda beshinchi va 2020 yilda to'rtinchi o'rinni egalladi.

Mane o'zining professional faoliyatini Liga 2-ning "Metz" klubida 19 yoshida boshladi, ammo u yakka mavsumdan so'ng 2012 yilda Avstriyaning "Red Bull Zaltsburg" klubiga 4 million evro evaziga qo'shildi va 2013-2014 yillarda liga va kubok ichki kubogini yutdi. mavsum. O'sha yozning oxirida Mane Angliyaning "Sauthempton" klubiga 11,8 million funt sterling evaziga o'tdi. U erda u eng tezkor xet-trik bo'yicha APLning yangi rekordini o'rnatdi, 2015 yilda "Aston Villa" ustidan 6: 1 hisobida g'alaba qozonganida 176 soniyada gol urdi.

U 2016 yilda Angliya Premer-ligasining "Liverpul" klubi bilan shartnoma imzoladi va uning maoshi 34 million funtni tashkil qiladi. "Liverpul" bilan Mane ularga 2018 va 2019 yillarda UEFA Chempionlar Ligasining final bosqichiga chiqishga yordam berdi va ikkinchisida g'alaba qozondi. Shuningdek, u Premer-liganing "Oltin butsa" sini yutib, 2018–19 mavsumda liganing eng yaxshi to'purari sifatida yakunlandi. Mane keyinchalik Liverpulning 2019–20 yilgi Premer-ligada g'alaba qozonib, 30 yillik chempionatdagi qurg'oqchilikni tugatishga yordam berdi.

Xalqaro miqyosda Mane 2012 yilda debyut qilganidan buyon Senegal tarkibida 75 o'yinda 23 golni ro'yxatdan o'tkazdi va hozirgi kunda o'z millatining eng yaxshi to'purarlari orasida uchinchi, barcha o'yinlarda esa beshinchi o'rinni egallab turibdi. U Senegal vakili sifatida 2012 yilgi Olimpiada o'yinlarida, shuningdek Afrika Millatlar Kubogining 2015 va 2017 yilgi nashrlarida qatnashgan. 2019 yildagi takrorlashda Mane Senegalni ikkinchi o'rinni egallashiga yordam berdi va bir yildan so'ng Afrikaning yilning eng yaxshi futbolchisi deb topildi. Mane, shuningdek, o'z millatini 2018 FIFA Jahon kubogida ishtirok etdi va musobaqadagi ikkinchi marta ishtirok etdi.

Maneni 2020 yilda Nyu-Afrika jurnali Afrikaning eng nufuzli 100 taligi qatoriga kiritgan.""",
    """Mohamed Salah Hamed Mahrous Ghaly (arab. Mحmd صlاح حاmd mحrوs غغlى, Misr arabcha talaffuzi: [mæˈħam.mæd sˤɑˈlɑːħ ˈɣæːli]; 1992 yil 15-iyunda tug'ilgan) - misrlik professional futbolchi, Premer-liganing «Liverpul» klubi forvardi sifatida o'ynaydi va sardorlar. Misr terma jamoasi. Dunyoning eng yaxshi o'yinchilaridan biri deb hisoblangan [6] [7] u o'zining tugashi, driblingi va tezligi bilan tanilgan.

Saloh o'zining katta faoliyatini Misrning "Al Mokavlon" klubida boshlagan va ko'p o'tmay Shveysariyaning "Bazel" klubiga ma'lum bo'lmagan haq evaziga yo'l olgan. Shveytsariyada uning o'yinlari Premer-liganing "Chelsi" sini o'ziga tortdi va ular 2014 yilda uni 11 million funt evaziga sotib olishdi. Ammo, u debyut mavsumida tejamkorlik bilan ishlatilgan va A Seriyaning "Fiorentina" va "Roma" jamoalariga ijaraga berib yuborilgan, ikkinchisi esa uni 15 million evro evaziga doimiy ravishda imzolagan. 2017 yilda "Roma" ning ikkinchi o'rinni egallashiga va klubning rekord ochko to'plashiga yordam berishdagi rolidan so'ng, Saloh Premer-ligaga qaytib, o'sha paytdagi klubning rekord narxi - 36,9 million funt evaziga "Liverpul" bilan shartnoma imzoladi.

Angliyadagi ikkinchi sehrida Saloh o'z o'yinini tabiiy qanot hujumchisidan forvardga moslashtirdi va o'zining debyut mavsumida 36 liga o'yinlarida 32 ta gol urib, APLning "Oltin butsa" sini yutdi va APLning 38- gol urish bo'yicha rekordini yangiladi. o'yin mavsumi. Salohning o'yinlari unga bir qator individual maqtovlarga sazovor bo'ldi, jumladan PFA futbolchilarining yilning eng yaxshi o'yinchisi. Shuningdek, u 2018 yil FIFAning eng yaxshi erkaklar o'yinchisi mukofotida uchinchi o'rinni egalladi. Keyingi mavsumda u Premer-liganing eng yaxshi to'purari sifatida yakunlandi va "Liverpul" ga UEFA Chempionlar Ligasining 2018-19 yilgi mavsumida g'alaba qozonib, g'olib chiqdi. Klubdagi uchinchi mavsumida u jamoaning 2019–20 yilgi Premer-ligada g'olib bo'lishiga yordam berdi, bu esa klubning 30 yillik chempionlik qurg'oqchiligini yakunladi.

Xalqaro miqyosda Saloh 2011 yilda o'zining birinchi debyutidan oldin Misrni yoshlar darajasida himoya qilgan. 2012 yilgi Yozgi Olimpiadadagi o'yinlaridan so'ng u CAF yilning eng istiqbolli afrikalik iste'dodi deb topildi. O'shandan beri u Misrga 2017 yilgi Afrika Millatlar Kubogi finaliga chiqishga yordam berdi va jamoaning 2018 yilgi FIFA Jahon chempionatiga chiqishiga yordam berish uchun CAF saralashi davomida eng yaxshi to'purar bo'ldi. Salah CAF afrikalik yilning eng yaxshi futbolchisi (2017 va 2018), BBC afrikalik yilning eng yaxshi futbolchisi (2017 va 2018) deb topildi va 2017 yilgi Afrika Millatlar Kubogi musobaqasi jamoasi va CAF yilning eng yaxshi jamoasi deb tan olindi. bir necha bor.""",
    """Raxim Shakil Sterling MBE (1994 yil 8-dekabrda tug'ilgan) - Angliya professional futbolchisi, Angliya premer-ligasining "Manchester Siti" klubi va Angliya terma jamoasida vinger va hujumkor yarim himoyachi sifatida o'ynaydi.

Yamaykada Yamaykalik ota-onada tug'ilgan Sterling 5 yoshida Londonga ko'chib o'tgan va 2010 yilda "Liverpul" bilan shartnoma imzolashidan oldin o'z faoliyatini "Kvins Park Reynjers" da boshlagan. 2014 yilda "Golden Boy" mukofotiga sazovor bo'lgan. 2015 yil iyul oyida uzoq tortishuvlardan so'ng "Manchester Siti" bilan yangi shartnoma imzolandi, u potentsial qiymati 49 million funt sterlingni tashkil qildi va bu o'sha paytdagi ingliz futbolchisi uchun to'langan eng yuqori narx. Keyin u «Manchester Siti» ga 2017–18 va 2018–19 mavsumlarda ketma-ket APL chempionligini qo'lga kiritishda yordam berdi. 2018–19 mavsumda u PFA Premer-ligasining yilning eng yaxshi jamoasi nomiga sazovor bo'ldi va PFA yilning eng yaxshi yosh o'yinchisi va FWA yilning eng yaxshi futbolchisini yutdi.

Yamayka vakili sifatida ham qatnashish huquqiga ega bo'lgan Sterling 2012 yil noyabr oyida Angliya terma jamoasida 16 yoshgacha, 17 yoshgacha, 19 yoshgacha va 21 yoshgacha bo'lgan yoshlar tarkibida maydonga tushganidan so'ng o'zining birinchi debyutini o'tkazdi. U 2014 yilgi Jahon chempionati, 2018 yilgi Jahon chempionati, UEFA Evro-2016 va UEFA Evro-2020 uchun Angliya tarkibida tanlangan.""",
    """Paul Labile Pogba (born 15 March 1993) is a French professional footballer who plays for Premier League club Manchester United and the France national team. He operates primarily as a central midfielder, but can also be deployed as an attacking midfielder, defensive midfielder and deep-lying playmaker.

Born in Lagny-sur-Marne, Pogba joined the youth team of Ligue 1 side Le Havre in 2007, before a protracted transfer brought him to Manchester United two years later. After beginning his senior career with Manchester United two years later, limited appearances persuaded him to depart to join Italian side Juventus on a free transfer in 2012, where he helped the club to four consecutive Serie A titles, as well as two Coppa Italia and two Supercoppa Italiana titles. During his time in Italy, Pogba further established himself as one of the most promising young players in the world and received the Golden Boy award in 2013, followed by the Bravo Award in 2014. In 2016, Pogba was named to the 2015 UEFA Team of the Year, as well as the 2015 FIFA FIFPro World XI, after helping Juventus to the 2015 UEFA Champions League Final, their first in 12 years.

Pogba's performances at Juventus led to him returning to Manchester United in 2016 for a then-world record transfer fee of €105 million (£89.3 million). The fee paid for him remains the highest paid by an English club. In his first season back, he won the League Cup and the Europa League. In the 2018–19 season, he was named to the PFA Team of the Year.

Internationally, Pogba captained France to victory at the 2013 FIFA U-20 World Cup and took home the award for the Best Player for his performances during the tournament. He made his debut for the senior team a year later and featured prominently at the 2014 FIFA World Cup, where he was awarded the Best Young Player Award for his performances. He later represented his nation at UEFA Euro 2016 on home soil, where he finished as a runner-up, before winning the 2018 FIFA World Cup, scoring in the final.""",
    """Kylian Mbappé Lottin (1998 yil 20-dekabrda tug'ilgan) - frantsuz professional futbolchisi, Liga 1 klubi Parij Sen-Jermeni va Frantsiya terma jamoasi forvardi sifatida o'ynaydi.

Mbappe o'zining yuqori martabasini Liga 1 klubi "Monako" da boshlagan va o'zining professional debyutini 2015 yilda 16 yoshida boshlagan. Ular bilan u Liga 1 unvoniga, Liga 1 yilning eng yaxshi yosh o'yinchisi va Golden Boy mukofotiga sazovor bo'lgan. 2017 yilda u Ligadagi raqiblari Parij Sen-Jermeni bilan dastlabki ijaraga oldi, bu esa 2018 yilda 180 million evroga transfer qilingan holda doimiy ravishda amalga oshirilib, uni ikkinchi eng qimmat futbolchi va eng qimmat o'spiringa aylantirdi. [4] U erda Mbappe uchta Liga 1 unvoniga sazovor bo'ldi, uchta Frantsiya kubogi g'olibiga aylandi, Liga 1da ikki marta yilning eng yaxshi futbolchisi deb tan olindi va ketma-ket uch mavsum Liga 1 to'purari sifatida yakunlandi. Shuningdek, u klub tarixidagi eng yuqori gol urish bo'yicha uchinchi o'rinni egallab turibdi.

Xalqaro miqyosda Mbappe 2017 yil 18 yoshida Frantsiyadagi katta debyutini o'tkazdi. JCh-2018da Mbappe Jahon kubogida gol urgan eng yosh frantsuz futbolchisiga aylandi va Peledan so'ng gol urgan ikkinchi o'spirin bo'ldi. Jahon kubogi finali. Frantsiya musobaqada g'olib chiqqanligi sababli u eng yuqori gol muallifi sifatida ikkinchi o'rinni egalladi va o'zining o'yinlari uchun "Yilning eng yaxshi yosh o'yinchisi va frantsuz futbolchisi" mukofotlarini oldi.""",
    """Antuan Grizmann (frantsuzcha talaffuzi: [ɑ̃twan ɡʁijɛzman]; 1991 yil 21 martda tug'ilgan) - fransiyalik professional futbolchi, Ispaniyaning «Barselona» klubi va Frantsiya terma jamoasida forvard sifatida o'ynaydi.

Frantsiyada tug'ilib o'sgan Grizmann o'zining katta karerasini 2009 yilda "Real Sosedad" da boshlagan va u bilan birinchi mavsumda Segunda Divizion unvoniga sazovor bo'lgan. 2014 yilda u "Atletiko Madrid" ga o'sha paytdagi klubning rekord qiymati - 30 million evro evaziga qo'shildi va bu erda debyut mavsumida klubning gol urish rekordini yangiladi va 2014-15 yilgi La Liga mavsumining eng yaxshi jamoasida qayd etildi. U 2016 yilda La Liganing eng yaxshi o'yinchisi deb tan olingan va 2016 yilgi "Oltin to'p" va 2016 yilgi FIFAning eng yaxshi erkaklar o'yinchisi sifatida uchinchi o'rinni egallagan. U 2018 yilda mukofotlar uchun mos ravishda uchinchi va oltinchi o'rinlarni egalladi, chunki u Madridning "Atletiko" siga UEFA Evropa Ligasini yutishida yordam berdi va finalda ikkita gol urdi. Grizmann shuningdek, Ispaniya Superkubogi-2014 va UEFA Superkubogi-2018 g'olibiga aylandi va klubning eng yuqori to'purarlari orasida beshinchi o'rinni egalladi. [7] 2019 yilda Grizmann "Barselona" bilan 120 million yevrolik transfer shartnomasini imzoladi va eng qimmat futbolchining to'rtinchisiga aylandi.

Xalqaro miqyosda Grizmann 2010 yil 19 yoshgacha bo'lgan UEFA Evropa chempionatida g'olib chiqdi va 23 yoshida Frantsiya terma jamoasida birinchi debyutini o'tkazdi va to'rtta yirik musobaqada qatnashdi. U eng yaxshi to'purar sifatida yakunlandi va turnirning eng yaxshi o'yinchisi sifatida ovoz berdi, chunki Frantsiya UEFA Evro-2016da ikkinchi o'rinni egalladi. Grizmann 2018 yilgi Jahon chempionatida eng yuqori gol muallifi sifatida "kumush butsa" ni qo'lga kiritdi, chunki Frantsiya musobaqada g'olib chiqdi. Shuningdek, u uchinchi eng yaxshi o'yinchi sifatida Bronza to'pini qo'lga kiritdi va finalda penaltini aniq bajarib, o'yinning eng yaxshi odami deb topildi.""",
    """Garri Edvard Keyn MBE (1993 yil 28-iyulda tug'ilgan) - ingliz professional futbolchisi, Angliya premer-ligasining «Tottenhem» klubida hujumchi bo'lib o'ynaydi va Angliya terma jamoasining sardori. Dunyoning eng yaxshi hujumchilaridan biri sifatida qaraladigan Keyn o'zining gol urish bo'yicha rekord ko'rsatkichi va o'yinni bog'lash qobiliyati bilan tanilgan.

Londonning Uoltem o'rmonida tug'ilgan va o'sgan Keyn o'z faoliyatini "Tottenxem" da boshladi, u erda jamoaning yoshlar akademiyasi orqali tez o'sib borgach, u 2009 yilda, 16 yoshida, katta yoshdagi jamoaga ko'tarildi. Leyton Orient, Milluoll, Lester Siti va Norvich Siti singari ingliz futbol piramidasi bo'ylab klublarga bir necha bor ijaraga berildi. 2014 yilda Maurisio Pochettino bosh murabbiy etib kelganidan so'ng Keynning "Tottenxem" dagi ishtiroki kuchayishni boshladi. Keyn klubdagi birinchi to'liq mavsumida barcha musobaqalarda 31 ta gol urdi, Premer-Liganing ikkinchi eng yuqori to'purari bo'ldi va PFA Young deb topildi. Yilning eng yaxshi o'yinchisi.

2015–16, 2016–17 va 2020–21 yilgi mavsumlarda Keyn chempionatning eng yaxshi to'purari sifatida yakunlandi. 2016–17 yilgi kampaniyada u "Tottenxem" ning musobaqa ikkinchi pog'onasini egallashiga yordam berdi va PFA muxlislarining "Yilning eng yaxshi o'yinchisi" sovrinini qo'lga kiritdi. Keyn 2017-18 yilgi mavsumda o'zining eng yaxshi kampaniyasini statistik jihatdan ro'yxatdan o'tkazdi, barcha musobaqalarda 48 o'yinda 41 ta gol urildi va keyingi mavsumda u UEFA Chempionlar Ligasida ikkinchi o'rinni egalladi. 2021 yil fevralda u "Tottenxem" ning rasmiy musobaqalardagi eng ko'p gol kiritgan ikkinchi futbolchisiga aylandi.

Keyn Angliya tarkibida 54 o'yinda 34 ta gol urgan. U har qanday yoshlar darajasida maydonga tushdi va gol urdi va 21 martda, 2015 yil mart oyida kattalar jamoasi bilan golli uchrashuvda maydonga tushdi va Keyn Angliya UEFA Evro-2016 saralashida muvaffaqiyatli ishtirok etdi va gol urdi va mamlakatni turnirning o'zida namoyish etdi. U 2018 yil Jahon chempionatidan oldin, 2018 yil may oyidan boshlab jamoa sardori etib tayinlangandi. O'sha musobaqada Keyn Angliyani to'rtinchi o'ringa olib chiqdi, bu ularning 1990 yildagi eng yuqori natijasi. Shuningdek, u Jahon kubogining eng yaxshi to'purari sifatida yakunlanib, "Oltin butsa" ni qo'lga kiritdi.""",
    """Arturo Erasmo Vidal Pardo (ispancha talaffuzi: [aɾˈtuɾo eˈɾazmo βiˈðal ˈpaɾðo]; [a] 1987 yil 22-mayda tug'ilgan) - chililik professional futbolchi, A Seriyaning «Inter» (Inter) klubi va Chili terma jamoasida yarim himoyachi sifatida o'ynaydi. "Yuventus" dagi faoliyati davomida namoyish etilishi, uni qattiq kurashganligi va tajovuzkor, qat'iyatli o'yin uslubi tufayli Italiya matbuoti tomonidan Il Gerriero ("Jangchi"), Rey Arturo ("Qirol Artur") va La Piranxa laqabiga sazovor bo'ldi.

Vidal o'z faoliyatini Colo-Colo-da boshlagan va u erda uchta Chili Primera Divizionida g'olib chiqqan. U Evropaga ko'chib o'tdi va u erda Bundesliganing "Bayer" (Leverkuzen) klubiga qo'shildi va u erda to'rt mavsum o'ynadi. Keyinchalik u 2011 yilda "Yuventus" ga o'tdi va u erda dunyo futbolining eng yaxshi yarim himoyachilaridan biri sifatida tanildi. "Yuventus" da u o'zining to'rt mavsumida ham Skudetti yutgan va ular uchun 2015 yilgi UEFA Chempionlar Ligasi finaliga chiqishida ajralmas bo'lgan. Vidal 2015 yildagi UEFA Evropaning eng yaxshi o'yinchisi mukofotining o'n kishilik ro'yxatiga kiritilgan. 2015 yil 28 iyulda Vidal Bundesligaga qaytib, «Bavariya» safiga qo'shildi va ketma-ket uch marta Bundesliga chempionligini qo'lga kiritdi. Myunxendagi uch yildan so'ng u La Liga grandi "Barselona" bilan shartnoma imzoladi va u erda sakkizinchi marta chempionlik unvonini qo'lga kiritdi.

Vidal 2007 yilda debyut qilganidan beri Chili terma jamoasi safida 120 ta o'yin o'tkazib, 2011, 2015, 2019 va 2021 yillarda Amerika Kubogi turnirlarida, shuningdek Amerika Kubogi Centenario, 2010 va 2014 FIFA Jahon chempionatlari va 2017 FIFAda o'ynagan. Konfederatsiyalar kubogi, o'z millatiga 2015 va 2016 yillarda Amerika Kubogida g'alaba qozonishda yordam berdi.""",
    """Mark-André ter Shtegen (nemischa talaffuzi: [ˌmaʁk ʔanˈdʁeː teːɐ̯ ˈsteːɡn̩; - ʔãˈd -]; 1992 yil 30 aprelda tug'ilgan) - nemis professional futbolchisi, Ispaniyaning «Barselona» klubi va Germaniya terma jamoasi darvozaboni sifatida o'ynaydi. O'zining reflekslari, uzatmalari va to'p o'ynash qobiliyati bilan tanilgan, u dunyoning eng yaxshi darvozabonlaridan biri hisoblanadi.

Myunxengladbaxning "Borussiya" si bilan Bundesligada to'rt mavsum o'ynaganidan so'ng, u "Barselona" ga 2014 yilda 12 million evro evaziga qo'shildi. U Ispaniyadagi birinchi mavsumida "Barselona" da Ispaniya Kubogi va UEFA Chempionlar Ligasida o'ynab treblga erishdi.

Ter Shtegen Germaniyaning bir nechta yoshlar darajasida vakili bo'lgan va 2012 yilda katta xalqaro debyutini o'tkazgan. U UEFA Evro-2016 yarim finaliga chiqqan va 2017 yilgi FIFA Konfederatsiyalar kubogini yutgan nemislar tarkibiga kirgan, shuningdek nemis a'zosi bo'lgan. 2018 FIFA Jahon chempionatida qatnashgan tomon.""",
    """Xordi Alba Ramos (1989 yil 21 martda tug'ilgan) - ispaniyalik professional futbolchi, u «Barselona» va Ispaniya terma jamoasining chap qanot himoyachisi sifatida o'ynaydi.

Alba faoliyatini "Barselona" da boshlagan, ammo u juda kichik deb hisoblangandan so'ng qo'yib yuborilgan. Kornellaga qo'shilgandan so'ng u Valensiyaga ko'chib o'tdi. 2012 yilda u Barselonaga qaytdi, u bilan o'n oltita asosiy sovrinni qo'lga kiritdi, shu jumladan beshta La Liga chempioni, beshta Kopas del Rey va UEFA Chempionlar Ligasi.

23ta o'yinda g'alaba qozongan va yoshlar darajasida bitta gol urganidan so'ng, Alba Ispaniyada 2011 yilda o'zining birinchi debyutini o'tkazgan. U UEFA Evro-2012da g'olib chiqqan jamoaning ajralmas a'zosi bo'lgan va 2014 yilda FIFA Jahon chempionatida ham tarkibga kirgan. va 2018 yil, va 2016 va 2020 yillarda Evropa chempionati.""",
  ];
}